edenred_dbt_core:
  target: "{{ env_var('DEFAULT_TARGET') }}"
  outputs:

    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('DEV_PROJECT') }}"
      dataset: "{{ env_var('DEV_DATASET') }}"
      threads: 16
      keyfile: "{{ env_var('DEV_KEYFILE') }}"
      timeout_seconds: 300
      location: "US"
      priority: "interactive"
      retries: 1

    ci:
      type: bigquery
      method: service-account
      project: "{{ env_var('CI_PROJECT') }}"
      dataset: "{{ env_var('CI_DATASET') }}"
      threads: 16
      keyfile: "{{ env_var('CI_KEYFILE') }}"
      timeout_seconds: 300
      location: "US"
      priority: "interactive"
      retries: 1

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROD_PROJECT') }}"
      dataset: "{{ env_var('PROD_DATASET') }}"
      threads: 16
      keyfile: "{{ env_var('PROD_KEYFILE') }}"
      timeout_seconds: 300
      location: "US"
      priority: "interactive"
      retries: 1

elementary:
  target: default
  outputs:
    default:
      type: bigquery
      method: service-account
      project: "{{ env_var('ELEMENTARY_PROJECT') }}"
      dataset: "{{ env_var('ELEMENTARY_DATASET') }}"
      threads: 16
      keyfile: "{{ env_var('ELEMENTARY_KEYFILE') }}"
      timeout_seconds: 300
      location: "US"
      priority: "interactive"
      retries: 1
